
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mou?serverTimezone=GMT%2B8
    username: root
    password: 123456
  application:
    name: AIVoiceChat
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode  # 通义千问
      api-key: sk-74a9cca57479408081e1ee08143c1399
      chat.options:
        model: qwen-plus
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: deepseek-r1:7b
  data:
    redis:
      host: 192.168.150.101
logging:
  level:
    org.springframework.ai: debug
    com.itheima.ai: debug

# UnifiedTTS API 配置
unifiedtts:
  api:
    base-url: https://unifiedtts.com  # UnifiedTTS API 基础URL
    key: tts_XufzdwlpBACgWkfYRPMhID--RBVjCSl0z52aDnpt5LM            # 您的API Key
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com # 你的Endpoint
    access-key-id: LTAI5t7SYH2mNQEMbRAYVpZ8
    access-key-secret: vfkHZPKPcscvVX7IQ3I6iA0Fly7KkG
    bucket-name: kczx-interview
    url-expire-time: 3600 # 签名URL有效时间（秒）
# ASR (语音识别) 服务配置
asr:
  service:
    type: baidu  # 可选: baidu, azure, local
  baidu:
    api-key: K3JrvZcB76dmPjGCCWkalF8P      # 百度语音识别 API Key
    secret-key: hIFbyDCB9TPjsQbHdKH42ShKqbuLsYg7 # 百度语音识别 Secret Key
  azure:
    subscription-key: your-azure-subscription-key  # Azure 语音服务订阅密钥
    region: eastus                                  # Azure 服务区域
  aliyun:
    access-key-id: LTAI5tSdc2mjXwX599WW91Pa        # 阿里云AccessKey ID
    access-key-secret: 257WOqcKc7A8RsK3wokO4WdwkY2p9Z # 阿里云AccessKey Secret
    app-key: Nom6NzshXiZVRIbI                  # 阿里云语音识别AppKey
    region-id: cn-shanghai                     # 阿里云区域 ID
    endpoint: nls-filetrans.cn-shanghai.aliyuncs.com # 阿里云录音文件识别端点
    oss:
      bucket-name: kczx-interview              # OSS存储桶名称
      endpoint: oss-cn-hangzhou.aliyuncs.com   # OSS端点
      url-prefix: https://kczx-interview.oss-cn-hangzhou.aliyuncs.com # OSS访问URL前缀
      url-expire-time: 3600 # 签名URL有效时间（秒）
  temp-dir: temp/audio               # 临时文件目录